-- Generated from src/content/seed.ts (scripts/gen-content-seed.ts). Do not edit by hand.
-- Manual-derived content and checklists (spec §7.0/§11). Apply after seed.sql.

do $$
begin
  if not exists (select 1 from public.task where source = 'manual') then
    insert into public.task (id, title, "group", phase, source, done, created_at) values
    (gen_random_uuid(), 'ウェルカムドリンク（梅ジュース・みかん）を用意', 'daily', 'midday_prep', 'manual', false, now()),
    (gen_random_uuid(), '共用部を清掃', 'daily', 'midday_prep', 'manual', false, now()),
    (gen_random_uuid(), 'ベッドメイク（本日の宿泊数分）', 'daily', 'midday_prep', 'manual', false, now()),
    (gen_random_uuid(), 'アメニティを補充', 'daily', 'midday_prep', 'manual', false, now()),
    (gen_random_uuid(), 'コーヒー豆の容器を補充', 'daily', 'midday_prep', 'manual', false, now()),
    (gen_random_uuid(), '和室ちゃぶ台のみかんを補充', 'daily', 'midday_prep', 'manual', false, now()),
    (gen_random_uuid(), 'ドミトリーを清掃', 'daily', 'cleaning', 'manual', false, now()),
    (gen_random_uuid(), 'シャワー・トイレを清掃', 'daily', 'cleaning', 'manual', false, now()),
    (gen_random_uuid(), '使用済みリネンを洗濯 → 乾燥', 'per_checkout', 'cleaning', 'manual', false, now()),
    (gen_random_uuid(), '火の始末（BBQ・焚き火）', 'daily', 'evening_close', 'manual', false, now()),
    (gen_random_uuid(), 'スタッフルームを施錠', 'daily', 'evening_close', 'manual', false, now()),
    (gen_random_uuid(), '玄関の戸締りを確認（遅着がいる日は施錠しない）', 'daily', 'evening_close', 'manual', false, now()),
    (gen_random_uuid(), '引き継ぎを投稿', 'daily', 'evening_close', 'manual', false, now()),
    (gen_random_uuid(), '翌朝バナナをセット（宿泊数 +2）', 'daily', 'morning_prep', 'manual', false, now()),
    (gen_random_uuid(), '翌朝のコーヒーを準備', 'daily', 'morning_prep', 'manual', false, now()),
    (gen_random_uuid(), 'ゴミ出し（最後に帰る人）', 'daily', 'morning_prep', 'manual', false, now());
  end if;
end $$;

insert into public.content (id, kind, slug, title, body, phase, lang, photo_paths, status, updated_at) values
  (gen_random_uuid(), 'manual', 'manual-welcome', 'はじめに', 'KRAFT BASE は熊野古道・小口のゲストハウス。「Unplug to recharge.」歩く人が静かに整う場所として迎える。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-facility', '施設・設備・館内ルール', 'ドミトリー、和室、共用キッチン、無料の洗濯機・乾燥機、Wi-Fi、屋外喫煙所。21:00以降は静かに。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-mindset', '接客の基本姿勢', '勝手に足さない。まず運営に提案。引き算で、取りこぼさず、押し付けない。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-checkout', '朝：チェックアウト対応', 'コーヒーとバナナを案内。翌朝のバスを前夜に伝える。お礼/レビュー依頼は予約サイト経由（対面では依頼しない）。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-midday', '日中：清掃・洗濯・準備', '清掃・洗濯・ベッドメイク・補充。受付準備を15:00までに整える。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-afternoon', '午後：チェックイン業務', '名前確認、パスポート確認（法定）、ベッド案内、館内案内。ウェルカムドリンクを出す。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-evening', '夜：交流と見送り', '弁当配達、火打石のお見送り、翌朝の案内。到着済みのゲストから順に。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-foreign', '外国人ゲスト対応', '英語の基本セットで対応。込み入った会話は受付iPadの翻訳アプリ。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-family', 'ファミリー対応', '夏の川遊びは安全な浅瀬を案内。増水時は中止を促す。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'manual', 'manual-workation', 'ワーケーション対応', 'オフシーズンの長期滞在。Wi-Fi と静かな作業環境を案内。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'procedure', 'proc-checkin', 'チェックイン手順', '名前確認 → パスポート確認（法定）→ 用紙記入 → ベッド案内 → 館内案内 → ウェルカムドリンク。', 'midday_prep', null, '{}', 'ready', now()),
  (gen_random_uuid(), 'procedure', 'proc-welcome-drink', 'ウェルカムドリンクの一言', '「梅ジュースとみかんをどうぞ。地元のものです。」到着のねぎらいとともに出す。', 'midday_prep', null, '{}', 'ready', now()),
  (gen_random_uuid(), 'procedure', 'proc-shower', 'シャワー案内', 'シャワー・トイレの場所と使い方、タオルの位置を案内する。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'procedure', 'proc-kamidana', '神棚の作法', '二礼・二拍手・一礼。翌朝、希望者がご自分の手で安全祈願をできる。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'procedure', 'proc-hiuchi', '火打石（切り火）の進行', '出かける人の背後で火打石と火打金を打ち合わせ火花を散らし、安全を願う。固有の石・道具・保管場所・声かけ・辞退時対応はモーリーと実演して確定。', 'evening_close', null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'procedure', 'proc-payment', '決済の使い方（Square / PayPay）', '館内販売の決済手順。具体操作は要確認。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'procedure', 'proc-bento', '弁当の受け取り・見分け', '肉のおくだの弁当。ベジタリアンは緑シール。受け取り方法・見分けは要確認。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'procedure', 'proc-bbq', 'BBQ の運用', '火気の扱い、片付け、火の始末。固有の運用は要確認。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'procedure', 'proc-claim', 'クレーム対応', 'まず傾聴し謝意を示す。その場で判断せず運営に確認・連絡。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'procedure', 'proc-emergency', '緊急時手順', '緊急は電話。警察110／消防・救急119。重症は119。運営（肉のおくだ）080-8032-9762。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'area', 'area-trails', '熊野古道（小雲取越・大雲取越）', '小雲取越：小口→請川/本宮 約13km・約4時間30分。大雲取越：那智大社→小口 約14.5km・中辺路最難関。古道上に売店・自販機なし。昼食・水は出発前に用意。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'area', 'area-bus', '交通（バス）', 'JR新宮駅 ⇄ 小口は神丸（または志古）で乗り換え。便数は少ない。最新の時刻表は要確認、受付に紙を常備。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'area', 'area-taxi', 'タクシー', '新宮市内のタクシー手配（距離が長く高額）。事業者名・概算料金は要確認。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'area', 'area-shop', '買い物・売店', '小口にコンビニ・スーパーなし。最寄りは新宮方面で約1時間。直近店舗と距離は要確認。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'area', 'area-river', '川遊び（夏）', '赤木川・小口川は清流。安全な浅瀬・更衣/トイレの場所は現地確認。増水時は中止。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'emergency', 'emergency-contacts', '緊急連絡先', '警察 110 ／ 消防・救急 119 ／ 運営（肉のおくだ）080-8032-9762。緊急は電話。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'emergency', 'emergency-hospital', '医療機関', '救急・入院は新宮市立医療センター 0735-31-3333。日中の軽症は熊野川診療所（住所・電話・診療時間は要確認）。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'emergency', 'emergency-disaster', '想定災害', '主リスクは熊野川・赤木川の河川氾濫と土砂災害。大雨・台風時は警報を待たず早めの自主避難を。', null, null, '{}', 'ready', now()),
  (gen_random_uuid(), 'emergency', 'emergency-shelter', '避難場所', '小口自然の家（熊野川町上長井398、0735-45-2434）が現実的な拠点。小和瀬・小口地区の正式な指定避難場所は要確認。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'emergency', 'emergency-aed', 'AED', '最寄りのAED設置場所は要確認（小口自然の家・公民館等）。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'emergency', 'emergency-roster', '法定名簿の保管', '宿泊者名簿の保管場所は未定。保管場所・保存期間・施錠を決めて追記する。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'price', 'price-list', '館内販売の価格', '飲み物・軽食・物販の価格表。要確認。', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-linen', 'リネン棚', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-cleaning', '清掃用具', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-amenities', 'アメニティ補充', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-welcome-drink', 'ウェルカムドリンク', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-coffee', 'コーヒー / 朝食在庫', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-firstaid', '救急箱', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-extinguisher', '消火器', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-router', 'Wi-Fi ルーター', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-locker', 'ロッカー', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-roster', '名簿用紙', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-guide', '施設案内', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'location', 'location-trash', 'ゴミ集積 / 収集', '', null, null, '{}', 'needs_input', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-ようこそ、KRA', 'ようこそ、KRAFT BASE へ。', 'Welcome to KRAFT BASE.', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-少々お待ちくださ', '少々お待ちください。', 'One moment, please.', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-お名前を教えてく', 'お名前を教えてください。', 'May I have your name, please?', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-パスポートを見せ', 'パスポートを見せていただけますか？（法律上の義務です）', 'May I see your passport? It is a legal requirement for foreign guests.', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-下の段と上の段、', '下の段と上の段、どちらがお好みですか？', 'Would you prefer the lower bunk or the upper one?', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-シャワーとトイレ', 'シャワーとトイレはこちらです。', 'The showers and toilets are this way.', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-洗濯機と乾燥機は', '洗濯機と乾燥機は無料でお使いいただけます。', 'The washer and dryer are free to use.', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-21:00以降は', '21:00以降はお静かにお願いします。', 'Please keep the noise down after 9 PM.', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-コーヒーとバナナ', 'コーヒーとバナナはご自由にどうぞ。', 'Please help yourself to coffee and bananas.', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-良い旅を！', '良い旅を！', 'Have a great hike!', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-en-翻訳アプリを使い', '翻訳アプリを使いますね。', 'Let me use a translation app.', null, 'en', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-de-ようこそ（独）', 'ようこそ（独）', 'Willkommen!', null, 'de', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-de-見送り（独）', '見送り（独）', 'Gute Wanderung!', null, 'de', '{}', 'ready', now()),
  (gen_random_uuid(), 'phrase', 'phrase-it-見送り（伊）', '見送り（伊）', 'Buon cammino!', null, 'it', '{}', 'ready', now())
on conflict (slug) do nothing;
